#!/bin/bash
# Auto-generated by install.sh — do not edit manually; re-run install.sh.
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
cd "/Users/christopherwood/Projects/SunfishSoftware/the-inverted-stack/web"
"/Users/christopherwood/.nvm/versions/node/v24.15.0/bin/npm" run build
exec "/Users/christopherwood/.nvm/versions/node/v24.15.0/bin/node" server.js
